language: node_js
node_js:
- '4'
- '5'
- '6'
sudo: false
cache:
  directories:
  - node_modules
  - build_tools/amov_venv
install:
- npm install -g grunt-cli
- npm install
- build_tools/install-amo-validator.sh
- (mkdir build_tools/spidermonkey && cd build_tools/spidermonkey && wget https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/jsshell-linux-x86_64.zip && unzip jsshell-linux-x86_64.zip && ln -sf `pwd`/js ../amov_venv/bin/)
before_script:
- $(npm bin)/crx keygen .
- mv key.pem ~/.ssh/chrome-apps.pem
script:
- grunt
- build_tools/validate-xpi.sh
env:
- INSTALL_VIRTUALENV=1
